### ISSUE TITLE
Publishing to the Maven Central

### ISSUE THREAD

**Issue by plokhotnyuk** [rallyhealth/weePickle#10]
Currently Bintray returns `504` or  time-outing for some build runs on CI:
```
 https://dl.bintray.com/rallyhealth/maven/com/rallyhealth/weepickle-v1_2.13/1.0.1/weepickle-v1_2.13-1.0.1.pom (Server returned HTTP response code: 504 for URL: https://dl.bintray.com/rallyhealth/maven/com/rallyhealth/weepickle-v1_2.13/1.0.1/weepickle-v1_2.13-1.0.1.pom) while downloading https://dl.bintray.com/rallyhealth/maven/com/rallyhealth/weepickle-v1_2.13/1.0.1/weepickle-v1_2.13-1.0.1.pom
```
```
download error: Caught java.net.ConnectException: Operation timed out (Connection timed out) (Operation timed out (Connection timed out)) while downloading https://dl.bintray.com/rallyhealth/maven/com/rallyhealth/weepickle-implicits-v1_2.13/1.0.1/weepickle-implicits-v1_2.13-1.0.1.pom
```

Please consider promotion of binaries to the Maven Central.

**Comment by htmldoug** [comment]
Agreed. Bintray definitely supports syncing to maven central--we just need to set that up. Would benefit all our libs. cc: @usufruct99 @jeffmay

**Comment by plokhotnyuk** [comment]
Come on, guys! Each time when the build fails I remember about this ticket:
```
2020-05-19T15:41:55.8611030Z [error]   download error: Caught java.io.IOException: Server returned HTTP response code: 504 for URL: https://dl.bintray.com/rallyhealth/maven/com/rallyhealth/weepickle-v1_2.12/1.0.1/weepickle-v1_2.12-1.0.1.pom (Server returned HTTP response code: 504 for URL: https://dl.bintray.com/rallyhealth/maven/com/rallyhealth/weepickle-v1_2.12/1.0.1/weepickle-v1_2.12-1.0.1.pom) while downloading https://dl.bintray.com/rallyhealth/maven/com/rallyhealth/weepickle-v1_2.12/1.0.1/weepickle-v1_2.12-1.0.1.pom
```

**Comment by htmldoug** [comment]
We use a caching proxy internally, so if bintray has been unavailable, that's probably why we didn't notice.

How often has it been failing? Just once or regularly?

**Comment by plokhotnyuk** [comment]
The Bintray repositories return 504 often these days. Not only your repository is affected: sbt plugins, webjars, etc.

[I had tried caching of dependencies](https://github.com/olafurpg/setup-scala/issues/5) for GitHub Actions CI too, but cache size grows and slowdowns the build.

Currently, I'm looking for any tricks on how to minimize those issues. A good option would be disabling downloading of sources and javadocs for CI builds.

**Comment by htmldoug** [comment]
Oof! Thanks for letting me know.

> I'm looking for any tricks on how to minimize those issues.

For reference, we run a private artifactory server backed by S3 and set up as a proxy. Heavy, but effective.

You've been so generous adding us to your benchmarks. I don't want your kindness punished with build failures. I'll spend some time today looking into setting up maven central.

**Comment by htmldoug** [comment]
I've put in a request to bintray to sync to JCenter. Looks like that'll unlock syncing from bintray to maven central.

**Comment by htmldoug** [comment]
https://mvnrepository.com/artifact/com.rallyhealth/weepickle-v1
