### ISSUE TITLE
hyphens in identifier name don't work with serialization/de-serialization

### ISSUE THREAD

**Issue by madhura90** [rallyhealth/weePickle#110]
I have a case class here with a hyphen in the identifier:
```
case class test(
  `name-withhyphen`: String
)

object test {
  implicit val rw: FromTo[test] = macroFromTo
}
```
When serializing/deserializing like this, I get:

```
val request = {"name-withhyphen":"name"}
request.validate(ToScala[test])
```

I get this error: `+com.rallyhealth.weepickle.v1.core.Abort: missing keys in dictionary: name$minuswithhyphen []`

**Comment by htmldoug** [comment]
Porting https://github.com/com-lihaoyi/upickle/pull/366 might resolve this.
