### ISSUE TITLE
Make XML support more discoverable

### ISSUE THREAD

**Issue by OndrejSpanel** [rallyhealth/weePickle#111]
After reading this project readme I supposed it is ready to use to parse XML encoded data:

> A stable JSON, YAML, MsgPack, XML, etc. serialization framework based

I did not find any documentation on how to use XML, and v1.jackson package does not seem to contain any XML code. If there is no real XML support, please, do not advertise it in the readme.

See also https://users.scala-lang.org/t/question-on-xml-to-json-with-weepickle-or-upickle/6512/2:

> The XML aspect is a little aspirational, I’m afraid – it should be straightforward in theory, but nobody’s actually done it yet.

**Comment by htmldoug** [comment]
Hi @OndrejSpanel. For XML support, you need to pull in https://mvnrepository.com/artifact/com.rallyhealth/weexml-v1. README needs to be updated to mention that. Once you pull in the jar, the following blurb from the readme should work:

```
FromScala(Foo(1)).transform(ToXml.string)            ==> """<root><i>1</i></root>"""
```

Note that the XML and JSON feature sets don't translate one-to-one. The output is currently "whatever jackson does."

**Comment by OndrejSpanel** [comment]
Actually I need to read XML files, not write them. The way I do it now is I use scala-xml to parse XML and then [json4s](https://github.com/json4s/json4s) `toJson(xml)` to convert to Json and process that,

Even if that kind of works , my expectations after reading the readme were a lot different, it did not stress the serialization is first and mostly JSON.

**Comment by htmldoug** [comment]
Reading XML files with [FromXml](https://github.com/rallyhealth/weePickle/blob/v1/weexml/src/main/scala/com/rallyhealth/weejson/v1/xml/FromXml.scala) should work as well. For example:

```scala
FromXml("""<root><i>1</i></root>""").transform(ToJson.string)
```

**Comment by OndrejSpanel** [comment]
`FromXml` looks interesting. Could it be perhaps made more discoverable somehow, e.g. adding a section into the readme about this approach?
