### ISSUE TITLE
Add a Play BodyParser for weePickle

### ISSUE THREAD

**Issue by jducoeur** [rallyhealth/weePickle#14]
We've talked about this, but so that we formally keep track of it:

One point of friction for full-throated usage of weePickle is HTML bodies in Play.  Parsing a JSON body with play-json is very easy; doing so with weePickle requires an annoying amount of ceremony.

Like would be made much easier if we had a weePickle BodyParser, similar to the one that exists for play-json.  In theory, this should be straightforward monkeywork, dictated by the BodyParser API, but somebody needs to dig in and do the work.

Obviously, this should only exist in the Play artifacts -- we don't want to drag Play dependencies into the weePickle core.

I'm assigning this to myself, and will poke at it when I have time, but if somebody else finds it urgent and wants to grab it, feel free.

**Comment by htmldoug** [comment]
https://github.com/AudaxHealthInc/lib-weepickle-spices/pull/4. Would be good to open source after we battle test a bit. It also has dependencies on the lib-stream-util akka stuff, so we'd have to find a place for it.

**Comment by htmldoug** [comment]
Solved by https://github.com/AudaxHealthInc/lib-weepickle-spices/pull/18 & https://github.com/AudaxHealthInc/lib-weepickle-spices/releases/tag/v1.4.0
