### ISSUE TITLE
We should have property-based tests for serialization / deserialization

### ISSUE THREAD

**Issue by jducoeur** [rallyhealth/weePickle#29]
This sort of problem, where we are supporting combinatoric products of many fields of many different types, is well-suited to property-based testing.  On general principles, we really ought to put together a suite that uses either ScalaCheck or ScalaTest's new internal property-based testing to push the edge cases and try things in combination.

The one complication here is that we should *ideally* construct data structures in property-based ways and try the macros out on them.  I suspect that isn't feasible -- there's a serious compile-time vs runtime impedance mismatch here -- but it's worth thinking about.

**Comment by htmldoug** [comment]
Added in #37.
