### ISSUE TITLE
Optimize macro-generated visitKeyValue(String)

### ISSUE THREAD

**Issue by htmldoug** [rallyhealth/weePickle#37]
Current implementation of `visitKeyValue(String)` is O(n) and showing up under the profiler. This can almost certainly be optimized.

Ideas:
- [StringMatrix](https://github.com/zio/zio-json/blob/907b2e31068af55b5381d7880548078a1bdbc9a6/src/main/scala/zio/json/internal/lexer.scala#L387) looks like it might be doing something clever, but suboptimal
- perhaps macro should generate some branchy ifs based on length and charAt(i).
- simple HashMap[String, Int]? Unfortunately, that'd force `CharSequence.toString()`. :\

**Comment by SCKelemen** [comment]
Gotta go fast

**Comment by htmldoug** [comment]
Fixed by #38. Thanks @russellremple!
