### ISSUE TITLE
Unable to import yaml in version 1.4.0

### ISSUE THREAD

**Issue by ashwinbhaskar** [rallyhealth/weePickle#68]
From the examples, doing this import
```
import com.rallyhealth.weejson.v1.yaml.{FromYaml, ToYaml}
```
gives the error `object yaml is not a member of package com.rallyhealth.weejson.v1`

**Comment by jducoeur** [comment]
Hmm.  Just guessing (I haven't tried using the YAML functionality myself), but it looks to me like that requires an additional dependency -- I would try:
```
libraryDependencies += "com.rallyhealth" %% "weeyaml-v1" % "version"
```

**Comment by ashwinbhaskar** [comment]
@jducoeur yes, that did the work. Would you like me to update the readme with this?

**Comment by jducoeur** [comment]
I'm not the primary author, but I suspect a PR would be welcomed -- thanks!
