### ISSUE TITLE
Writing to a file with ToYaml wraps values in double quotes

### ISSUE THREAD

**Issue by ashwinbhaskar** [rallyhealth/weePickle#70]
This is the code

```
val yml = FromYaml(Files.newInputStream(Paths.get("foo/zoo.yml"))).transform(Value)
yml.apply(StringSelector("outer-key-1")).apply(StringSelector("outer-key-2")).update(StringSelector("some-key"), "some new value here") 
yml.transform(ToYaml.outputStream(Files.newOutputStream(Paths.get("foo/bax.yml")))) 
```

Content of `zoo.yml` before
```
...
some-key: old-value
...
```
after the transformation content of `bax.yml`
```
...
some-key: "some new value"  //the new value is wrapped in double quotes
...
```
It shouldn't be wrapping the value with double quotes right?

**Comment by htmldoug** [comment]
This behavior comes from https://github.com/FasterXML/jackson-dataformats-text. Given YAML's rather interesting value literals, I'm not surprised that jackson quotes everything by default.

For example, consider the unquoted country code of [Norway](https://laendercode.net/en/country/no) in YAML:
```scala
FromYaml("""countryCode: NO""").transform(ToJson.string) // {"countryCode":false}
```

I found that `YAMLGenerator` has a [MINIMIZE_QUOTES](https://github.com/FasterXML/jackson-dataformats-text/blob/adffd89ab713fa95721bd06194088ca66b959976/yaml/src/main/java/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.java#L84-L92) feature that may be what you're looking for. You can make your own [ToYaml](https://github.com/rallyhealth/weePickle/blob/28fabe8e96ab4246742cd1d4470d69672ebfa623/weejson/yaml/src/com/rallyhealth/weejson/v1/yaml/ToYaml.scala#L6) by passing a factory with different feature flags.

```scala
object ToNakedYaml extends JsonGeneratorOps(new YAMLFactory().enable(YAMLGenerator.Feature.MINIMIZE_QUOTES))

FromJson("""{"norway": "no", "sweden": "se"}""").transform(ToNakedYaml.string)
```

```yaml
---
norway: "no"
sweden: se
```

**Comment by htmldoug** [comment]
This seems worse than I initially thought. [Here](https://github.com/cblp/yaml-sucks/blob/master/README.md) are more YAML puzzlers. Looks like the spec is loose and YAML texts are open to different interpretations by different parsers!

If there's any chance that the output might be read by something other than the same version of the same library that emitted it, it seems better to quote everything explicitly.
